# travis

git:
  depth: 3

language: generic
os: linux
dist: bionic

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - bash --version
  - openssl version
  - shellcheck --version

script:
  - shellcheck create-client create-root-ca create-server create-signing-ca functions gen-html renew-cert revoke-cert show-status sign-csr
  - |
      bash --posix ./create-root-ca -l -d travis-ca <<EOF
      travis-ca
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate Authority
      rootCA_password
      rootCA_password
      EOF
  - cd travis-ca/
  - |
      bash --posix ./bin/create-server -s travis-server.bogus.com -a www.travis-server.bogus.com << EOF
      rootCA_password
      San Francisco
      Jurisdiction of travis-server.bogus.com
      EOF
  - |
      bash --posix ./bin/create-client -c travis-client << EOF
      rootCA_password
      San Francisco
      private
      travis-client@bogus.com
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/server/travis-server-bogus-com/travis-server-bogus-com.crt << EOF
      1
      y
      rootCA_password
      EOF
  - |
      bash --posix ./bin/create-signing-ca -d travis-signing << EOF
      rootCA_password
      travis-signing
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate travis-signing
      signCA_password
      signCA_password
      EOF
  - bash --posix ./bin/show-status
  - bash --posix ./bin/gen-html
  - cd travis-signing/
  - |
      bash --posix ./bin/create-server -s travis-server.bogus.com -a www.travis-server.bogus.com << EOF
      signCA_password
      San Francisco
      Jurisdiction of travis-server.bogus.com
      EOF
  - |
      bash --posix ./bin/renew-cert -s travis-server-bogus-com -t server << EOF
      signCA_password
      EOF
  - |
      bash --posix ./bin/create-client -c travis-client << EOF
      signCA_password
      San Francisco
      private
      travis-client@bogus.com
      EOF
  - |
      bash --posix ./bin/renew-cert -s travis-client -t client << EOF
      signCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/server/travis-server-bogus-com/travis-server-bogus-com.crt.old << EOF
      1
      y
      signCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/clients/travis-client/travis-client.crt.old << EOF
      5
      y
      signCA_password
      EOF
  - |
      openssl req -nodes -new -newkey rsa:2048 -sha256 -out csr.pem << EOF
      AU
      Some-State
      Locality
      Organization Name
      Organizational Unit Name
      csr-test
      test@bogus.com


      EOF
  - |
      bash --posix ./bin/sign-csr -c csr.pem << EOF
      signCA_password
      EOF
  - bash --posix ./bin/show-status
  - bash --posix ./bin/gen-html
